test :
			 g++ -std=c++0x -isystem ../../googlemock/include -isystem  \
			 ../../googletest/include -lpthread \
			 AlmacenTest.cpp \
			 ../../googletest/make/gtest_main.a ../../googlemock/make/gmock_main.a \
			 -o test.out
